[package]
name = "g-factor"
version = "0.1.0"
authors = ["mr-chrome <giovanni.crisalfi@gmail.com>"]
edition = "2018"

[dependencies]
gtk = "0.9.2"
glib = "0.10.3"
gio = "0.9.1"

cairo-sys-rs = "0.10.0"
cairo-rs = { version = "0.9.1" }
rand = "0.7.3"
tokio = { version = "0.3", features = ["full"] }
